apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api-gateway
        image: ghcr.io/nikita65288/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://config-service:8888/"
        - name: LOGSTASH_DESTINATION
          value: "logstash:5044"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION
          value: "86400000"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0"
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"  
