apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: media-service
        image: ghcr.io/nikita65288/media-service:latest
        ports:
        - containerPort: 9004
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-service:8888"
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_USER
          value: "user"
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: mongo-password
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0"
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"  
