apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: config-service
        image: ghcr.io/nikita65288/config-service:latest
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: "https://github.com/nikita65288/familiar-faces-config.git"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
          value: "nikita65288" 
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-secrets
              key: git-token  
        - name: GIT_TOKEN 
          valueFrom:
            secretKeyRef:
              name: git-secrets
              key: git-token
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0"
        resources:
          limits:
            memory: "512Mi" 
          requests:
            memory: "256Mi"
