apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: ghcr.io/nikita65288/config-service:latest
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: GIT_TOKEN 
          valueFrom:
            secretKeyRef:
              name: git-secrets
              key: git-token
