apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: notification-service
        image: ghcr.io/nikita65288/notification-service:latest
        ports:
        - containerPort: 9003
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://config-service:8888/"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0"
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"  
