apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ghcr.io/nikita65288/user-service:latest
        ports:
        - containerPort: 9001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-service:8888"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-password
        - name: DB_HOST
          value: "postgres"
