apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: user-service
        image: ghcr.io/nikita65288/user-service:latest
        ports:
        - containerPort: 9001
        env:
        - name: LOGSTASH_DESTINATION
          value: "logstash:5044"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://config-service:8888/"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: universal-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: universal-password
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/user_service_db"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0"
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"  
