apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: familiar-faces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: ghcr.io/nikita65288/chat-service:latest
        ports:
        - containerPort: 9002
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-service:8888"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: DB_HOST
          value: "postgres"
        # Get credentials from cluster Secrets
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: universal-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: universal-password 
